.\"
.\" Copyright (C) 2019 Arnaud Bonatti <arnaud.bonatti@gmail.com>
.\"
.\" This file is part of GNOME 2048.
.\"
.\" GNOME 2048 is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" GNOME 2048 is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with GNOME 2048.  If not, see <https://www.gnu.org/licenses/>.
.\"
.TH GNOME-2048 6 "2019\-10\-28" "GNOME"
.SH NAME
GNOME 2048 \- Obtain the highest possible tile
.SH SYNOPSIS
.B gnome-2048
.RI [ OPTION... ]
.SH DESCRIPTION
2048 is a highly addictive single-player game. Gameplay consists of joining numbers in a grid for obtaining bigger values.

Use your keyboard’s arrow keys or gestures to slide all tiles in the desired direction. Be careful: all tiles slide to their farthest possible positions, you cannot slide just one tile or one row or column. Tiles with the same value are joined when slided one over the other. After your turn, one new tile is added to the game.

Gnome 2048 only adds tiles of value 2, as opposed to the original 2048 game. Also, it allows you to play on grids of various size.
.SH OPTIONS
.TP
.B \-\-cli=<command>
Play in the terminal. See “--cli=help” for documentation.
.TP
.B \-s, \-\-size=<size>
Changes the size of the grid. Size must be between 2 and 9, or in the form 2x3.
.TP
.B \-v, \-\-version
Prints the program version and exits.
.P
This program also accepts the standard GTK+ options.
.SH AUTHORS
.B gnome-2048
was written by Juan R. García Blanco and is maintained by Arnaud Bonatti.
.P
This manual page was written by Arnaud Bonatti <arnaud.bonatti@gmail.com>.
